export const API_INVOCATION = "API_INVOCATION";
export const SHOW_TOAST_MESSAGE = "SHOW_TOAST_MESSAGE";
export const RESET_SHOW_TOAST_MESSAGE = "RESET_SHOW_TOAST_MESSAGE";
export const START_LOADER = "START_LOADER";
export const STOP_LOADER = "STOP_LOADER";

export const GET_SEARCH_PRODUCT_LIST="GET_SEARCH_PRODUCT_LIST"
export const GET_SEARCH_PRODUCT_LIST_SUCCESS="GET_SEARCH_PRODUCT_LIST_SUCCESS"
export const GET_SEARCH_PRODUCT_LIST_ERROR="GET_SEARCH_PRODUCT_LIST_ERROR"
export const RESET_SEARCH_PRODUCT_LIST="RESET_SEARCH_PRODUCT_LIST"


export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST"
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS"
export const GET_CATEGORY_LIST_ERROR = "GET_CATEGORY_LIST_ERROR"


export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST"
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS"
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR"