name: Deploy to GCP Storage Bucket

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install --force

    - name: Build
      run: npm run build

    - name: Upload to GCS bucket
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        source: build
        destination: gs://softpage-fastie.appspot.com
